sudo: required

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:nerdboy/embedded
  - sudo apt-get -qq update
  - sudo apt-get install libnanomsg-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox-travis 

# command to run tests, e.g. python setup.py test
script:
  - tox
