sudo: required

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

#env:
#  - TRAVIS_TAG="1.1.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y -u ppa:ubuntu-toolchain-r/test
  - sudo apt-get install -y --allow-unauthenticated build-essential cmake ninja-build

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# Build steps taken from
# https://github.com/nanomsg/nanomsg#build-it-with-cmake
install:
  - git clone --quiet --depth=100 "https://github.com/nanomsg/nanomsg.git" ./builds/nanomsg
      && pushd ./builds/nanomsg
  - export TRAVIS_TAG=$(cat .version)
  - git checkout -b "${TRAVIS_TAG}"
  - mkdir build && cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=${BUILD_TYPE:-Debug} ..
  - ninja
  - sudo cmake --build . --target install
  - sudo ldconfig && popd

# command to run tests, e.g. python setup.py test
script: LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib python setup.py test

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
